### ISSUE TITLE
Tableau tbw source not available

### ISSUE THREAD

**Issue by zwirbel** [brilliant-data/tableau-d3-sankey-demo#1]
Dear brilliant data
can you share the tabelau source data so I can ensure that I do not have any other issues, as the sankey currently does not show.
your tableau source data is published on the server that I do not have access to.
Can you make this available as well?
I am not familiar witht he coffee methods, and my understanding is the you are referring to apps.js which I assume is a combined version of various coffee files.

your help is highly appreciated.
regards,

**Comment by ghost** [comment]
The data used can be found in the app\sql folder
